
export interface Question {
  id: string;
  text: string;
  type: 'short_answer' | 'multiple_choice' | 'checkbox';
  options?: string[];
  correctAnswer?: string;
}

export interface Form {
  id?: string; // Optional because it's generated by DB
  code: string;
  title: string;
  description: string;
  questions: Question[];
  created_by?: string; // Supabase auth user id
  created_at?: string;
  time_limit?: number; // Time limit in minutes
}

export interface Response {
  id?: string;
  form_code: string;
  username: string;
  answers: Record<string, any>;
  submitted_at?: string;
}

// Helper to generate unique 6-digit code
export const generateUniqueCode = (): string => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};
